baseURL = 'https://jonathanchinwei.github.io/'
languageCode = 'en-us'
title = 'Jonathan Chin'
theme = 'cactus'

[[menu.main]]
name = 'Home'
url = '/'
weight = 1

[[menu.main]]
name = 'Posts'
url = '/posts'
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[params]
colortheme = "classic"
description = """I'm  Jonathan. I graduated from the University of Toronto where I studied Economics and Data Analytics. I care mostly about donuts, macroeconomics and international relations. I founded and lead the [Sino-Southeast Initiative](sinosoutheastinitiative.com). Previously, I've interned at BCG, J.P.Morgan and the Malaysian central bank.

In a former life I was a debater and coach. In high school, I was a top ten debater at the world championships and was thereafter a coach for Team Malaysia 2022. 

I also take an interest in effective altruism. When I'm bored I play sports (badminton/swimming/frisbee) and music (piano/alto sax/guitar)."""

mainSection = "posts"
mainSectionTitle = "Blog"

showAllPostsOnHomePage = false
postsOnHomePage = 5

tagsOverview = false

[[params.social]]
  name = "email"
  link = "jonathan.chin@mail.utoronto.ca" # no need for "mailto:" at the start

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/jonathanchinwei/"

[[params.social]]
  name = "github"
  link = "https://github.com/jonathanchinwei"